### ISSUE TITLE
user authentication

### ISSUE THREAD

**Issue by traviskochel** [typeworld/typeworld#1]
I was wondering if the API documentation could provide a little more information, or suggestions for restricting downloads.

From my understanding anyone with the API endpoint link would be able to install the font, even if setting `requiresUserID`, `seatsAllowedForUser`, and `seatsInstalledByUser` flags, correct? The restriction would have to be done on the API?

I suppose we could generate a difficult to guess token for each user, rather than a user id, but still they could share that link with others?

Ideally, I wonder if it would be nice to have some kind of authentication mechanism, a 'sign in with type.world'(like sign in with facebook), so that our website could confirm the identity of the person who's installing. I realize this is a huge feature to add though...

**Comment by yanone** [comment]
Hi Travs. 
I'm happy you're looking into the project.

> From my understanding anyone with the API endpoint link would be able to install the font, even if setting requiresUserID, seatsAllowedForUser, and seatsInstalledByUser flags, correct? The restriction would have to be done on the API?

Yes.
`requiresUserID` is only for the app to know that it needs to send an `uninstallFont` request upon font removal.
`seatsAllowedForUser` is only for UI signaling. The actual download restrictions need to happen on the server side.
 
> I suppose we could generate a difficult to guess token for each user, rather than a user id, but still they could share that link with others?

The idea is that this `userID` is already difficult to guess by making it anonymous instead of your system’s official userID.
But the result remains. A shared link will provide access to the fonts, given that the API still allows further downloads for these particular fonts.
 
> Ideally, I wonder if it would be nice to have some kind of authentication mechanism, a 'sign in with type.world'(like sign in with facebook), so that our website could confirm the identity of the person who's installing. I realize this is a huge feature to add though...

Maybe not so huge.
I'm planning to add user accounts for the Type.World App, to synchronize and backup subscriptions for each user (at first, later also the actual font installations).
The font installation request could then include an `anonymousTypeWorldUserID` identifying the Type.World user account. You would then have to log that userID in your system and allow future access only from the same Type.World user account (even if it came from a different computer).

How does that sound?

Here's a catch, though: My idea is that users can share the subscriptions with each other, let’s say inside an office or a custom type work group. They would invite each other by email from inside the app.
Another user would then likely have another Type.World user account, and how do you then authenticate that other user, who has a legitimate right to use the fonts?

Then you would have to allow more user authentications for a particular subscription, and it's starting to feel a bit like a replication of the download restrictions by counting seats that are already in place (if you choose to implement them).

Please let me know what you think.

**Comment by yanone** [comment]
There is a way: Users can share a subscription with other users only through official Type.World user accounts instead of random email addresses. 
When that happens, the Type.World App would then have to announce the authentication of the new user to your server, but that would have to happen in a secretive way because this authentication could also be forged outside of the app. And then it's starting to get a bit weird and messy, honestly, and a lot to ask for the publishers to implement.

**Comment by traviskochel** [comment]
Yeah, I can see how this gets complicated real quick. Especially when allowing people to install on multiple computers.

> The font installation request could then include an anonymousTypeWorldUserID identifying the Type.World user account. You would then have to log that userID in your system and allow future access only from the same Type.World user account (even if it came from a different computer).

I wonder if something like this could work in a simpler way. Maybe the type.world app automatically assigns each installation with a unique identifier, but without requiring a sign up, or having to talk to a type.world database. Then the user can take that id and add it to a whitelist on the publisher's site? 

I suppose this could be done in a similar manner with the current setup though. The publisher's UI could allow a customer to generate multiple single use tokens/ids that can be used to install a particular font/family.

So, I guess going back to my opening question, maybe this isn't so much of a feature request. Maybe the API documentation could just outline some strategies or best practices of controlling access from the server side? It would be good to know what solutions are officially supported as the API evolves.

**Comment by yanone** [comment]
Before we talk further, it feels like you should take a look at the standalone reference server that I implemented (http://github.com/typeWorld/referenceServer). I didn’t write about the best practices yet, but it feels like this already contains what you are looking for, such as the `anonymousAppID` parameter that the app already sends.

This server is how I would implement it, but your own logic might differ. 
It logs each installation with the tuple `userID` (should be anonymous but doesn't have to), `anonymousAppID` and `fontID`. This is not a white list, but a ledger of the installations. When a font needs to be updated, it will first be uninstalled, so the installation removed from the ledger, then the new version installed instantly. 
(This is still debatable. A white list is also thinkable, but my approach definitely works)

In the reference server, this ledger is found in `seatTracking/seats.txt`. All the data is stored in files there. Obviously, you connect this to all your own data bases.

Theoretically, we could add the `typeWorldAnonymousUserID` parameter to each calls, which would be the Type.World App User Account that people can use to sync subscriptions. In fact I will definitely send the parameter once an account exists for a user, but I'm note sure yet what to do with it. However, each server could decide on its own what to do with it. Can definitely be used for stats of sorts.

I was thinking to make Type.World user accounts compulsory for commercial fonts (denoted in the JSON protocol by a font being `requiresUserID=True` as well as the JSON endpoint root being `public=True`.

This is for avoiding customer support issues for everyone once a user's computer gets lost or bricked and she/he needs to install a new OS installation and migrate fonts. The new font installations might get rejected then because the seat allowances have been previously exhausted. 
In combination with the Type.World user account, the user could then de-authorize an entire computer's worth of Type.World font installations at once. The central Type.World server would send uninstallation requests for all fonts of all the user's subscriptions using the `anonymousAppID` parameter of the bricked/lost computer that it has previously recorded. So we need to expect incoming uninstallation requests for fonts that haven't been installed, which I think is manageable.

At first I thought I need to record every single font installation in the central server, but figured later that it's not necessary because I can just send uninstall requests for all fonts regardless.

I want to postpone the recording of each individual font until later, until I have a good overview of the amount of user accounts and fonts installations that need to be dealt with. Logging only subscriptions for a user is negligible effort for the server.

I'll write all of this up into a best practice article soon.
Let me know what you think.

**Comment by yanone** [comment]
> I wonder if something like this could work in a simpler way. Maybe the type.world app automatically assigns each installation with a unique identifier, but without requiring a sign up, or having to talk to a type.world database. Then the user can take that id and add it to a whitelist on the publisher's site?
> 
> I suppose this could be done in a similar manner with the current setup though. The publisher's UI could allow a customer to generate multiple single use tokens/ids that can be used to install a particular font/family.

Both of the above ideas strike me as very complicated from a user experience point of view. 

The idea is to massively simplify the font installation experience. The total clicks it takes to install a font is 3: First on the "Install fonts in Type.World App" button the the publisher's web site, second on the unfortunate "Allow this link to be opened in Type.World App" dialog of the browser, and finally on any of the "Install (All) Font(s)" buttons in the actual fonts being offered in the app.

Requiring the user to add his installation to a white list is an obstacle, and so is requesting single use tokens. Any such behaviour, if necessary, must be automated, or else I don't see the point.

By the way, the single use token idea doesn't work if you also want to push font updates to users.

**Comment by jenskutilek** [comment]
I'm fine with a single "subscription link" being shared between people in an office, etc.

But I would like to see the "secret" (i.e. hard to guess) user ID/API key, whatever you may call it, not being sent as part of the URL for each update poll to the API server.

URLs are usually not considered secret, and may end up being part of analytics reports, stats, etc.

It would be better to define what part of the initial URL, used to launch the Type.World GUI app and start the subscription, constitutes the API key, then strip it from the URL for subsequent requests and send the API key in the HTTP request header instead. This way nobody will be able to see it (provided the connection uses HTTPS).

For example, the subscription link is:
`https://example.com/typeworld/3d096037fb5bc47a`

Type.World app would then use this URL for all further requests:

`https://example.com/typeworld?command=installableFonts`
`https://example.com/typeworld?command=installFont[...]`

with this request header:

`api_key: 3d096037fb5bc47a`

This is not as safe as e.g. OAuth, but in my opinion better than plain URL authentication.

**Comment by yanone** [comment]
Improved security design: https://type.world/developer#security-design
